
exports.UPDATE_USER = 'UPDATE_USER';
exports.UPDATE_PATH = 'UPDATE_PATH';
exports.UPDATE_PAGE_TITLE = 'UPDATE_PAGE_TITLE';
exports.UPDATE_ERROR_STATUS = 'UPDATE_ERROR_STATUS';
exports.FETCH_POST = 'FETCH_POST';
exports.QUERY_POSTS = 'QUERY_POSTS';
exports.REMOVE_ERRORS = 'REMOVE_ERRORS';

// Editor

exports.SAVE_POST = 'UPDATE_POST';
exports.DELETE_POST = 'DELETE_POST';
exports.TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
exports.TOGGLE_PREVIEW = 'TOGGLE_PREVIEW';
