
exports.UPDATE_PAGE = 'UPDATE_PAGE';
exports.UPDATE_PATH = 'UPDATE_PATH';
exports.FETCH_POST = 'FETCH_POST';
exports.QUERY_POSTS = 'QUERY_POSTS';
exports.REMOVE_ERRORS = 'REMOVE_ERRORS';

// Editor

exports.SAVE_POST = 'UPDATE_POST';
exports.DELETE_POST = 'DELETE_POST';
exports.TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
exports.TOGGLE_PREVIEW = 'TOGGLE_PREVIEW';
