
exports.UPDATE_PAGE = 'UPDATE_PAGE';
exports.UPDATE_ROUTE = 'UPDATE_ROUTE';
exports.FETCH_POST = 'FETCH_POST';
exports.QUERY_POSTS = 'QUERY_POSTS';

// Editor

exports.SAVE_POST = 'UPDATE_POST';
exports.TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
exports.TOGGLE_PREVIEW = 'TOGGLE_PREVIEW';
